/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Customers: () => import('#controllers/customers_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Products: () => import('#controllers/products_controller'),
}
