/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CustomerTransformer from '#transformers/customer_transformer'
import type OrderItemTransformer from '#transformers/order_item_transformer'
import type OrderTransformer from '#transformers/order_transformer'
import type ProductTransformer from '#transformers/product_transformer'

export namespace Data {
  export type Customer = InferData<CustomerTransformer>
  export namespace Customer {
    export type Variants = InferVariants<CustomerTransformer>
  }
  export type OrderItem = InferData<OrderItemTransformer>
  export namespace OrderItem {
    export type Variants = InferVariants<OrderItemTransformer>
  }
  export type Order = InferData<OrderTransformer>
  export namespace Order {
    export type Variants = InferVariants<OrderTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
}
